apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linode-token
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: main-secret-store #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: linode-token # Secret name in k8s
  data:
  - secretKey: password # which key it's going to be stored
    remoteRef:
      key: linode-token # Our secret-name goes here
