apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: main-secret-store
spec:
  provider:
    aws:  # set secretStore provider to AWS.
      service: SecretsManager # Configure service to be Secrets Manager
      region: us-east-1   # Region where the secret is.
      auth:
        secretRef:
          accessKeyIDSecretRef: 
            namespace: default
            name: awssm-secret # References the secret we created
            key: access-key  
          secretAccessKeySecretRef:
            namespace: default
            name: awssm-secret
            key: secret-access-key
